import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import App from '../App';

// Mock Konva and react-konva
vi.mock('react-konva', () => ({
  Stage: ({ children, onMouseDown, onMouseMove, onMouseUp }: any) => (
    <div data-testid="stage" onMouseDown={onMouseDown} onMouseMove={onMouseMove} onMouseUp={onMouseUp}>
      {children}
    </div>
  ),
  Layer: ({ children }: any) => <div data-testid="layer">{children}</div>,
  Line: (props: any) => <div data-testid="line" {...props} />,
  Rect: (props: any) => <div data-testid="rect" {...props} />,
  Circle: (props: any) => <div data-testid="circle" {...props} />,
  Text: (props: any) => <div data-testid="text" {...props} />,
  Arrow: (props: any) => <div data-testid="arrow" {...props} />,
  Image: (props: any) => <div data-testid="image" {...props} />,
  Group: (props: any) => <div data-testid="group" {...props} />,
  Transformer: (props: any) => <div data-testid="transformer" {...props} />,
}));

vi.mock('use-image', () => ({
  default: () => [null, { loading: false }]
}));

// Mock lucide-react icons
vi.mock('lucide-react', () => ({
  MousePointer2: () => <span>MousePointer2</span>,
  Hand: () => <span>Hand</span>,
  Pen: () => <span>Pen</span>,
  Highlighter: () => <span>Highlighter</span>,
  ArrowRight: () => <span>ArrowRight</span>,
  ArrowUpRight: () => <span>ArrowUpRight</span>,
  Square: () => <span>Square</span>,
  Circle: () => <span>Circle</span>,
  Type: () => <span>Type</span>,
  Eraser: () => <span>Eraser</span>,
  Undo2: () => <span>Undo2</span>,
  Redo2: () => <span>Redo2</span>,
  Trash2: () => <span>Trash2</span>,
  Download: () => <span>Download</span>,
  Image: () => <span>Image</span>,
  Scissors: () => <span>Scissors</span>,
  LayoutTemplate: () => <span>LayoutTemplate</span>,
  X: () => <span>X</span>,
  ZoomIn: () => <span>ZoomIn</span>,
  ZoomOut: () => <span>ZoomOut</span>,
  Group: () => <span>Group</span>,
  Ungroup: () => <span>Ungroup</span>,
  Shapes: () => <span>Shapes</span>,
  Scan: () => <span>Scan</span>,
  Minus: () => <span>Minus</span>,
  Lock: () => <span>Lock</span>,
  Unlock: () => <span>Unlock</span>,
  Grid3X3: () => <span>Grid3X3</span>,
  Settings: () => <span>Settings</span>,
  ChevronDown: () => <span>ChevronDown</span>,
  Upload: () => <span>Upload</span>,
  FileJson: () => <span>FileJson</span>,
  FileImage: () => <span>FileImage</span>,
  Copy: () => <span>Copy</span>,
  ClipboardPaste: () => <span>ClipboardPaste</span>,
  FolderOpen: () => <span>FolderOpen</span>,
  Plus: () => <span>Plus</span>,
  Check: () => <span>Check</span>,
  Anchor: () => <span>Anchor</span>,
  Palette: () => <span>Palette</span>,
  Eye: () => <span>Eye</span>,
  EyeOff: () => <span>EyeOff</span>,
  GripVertical: () => <span>GripVertical</span>,
  Magnet: () => <span>Magnet</span>,
  Info: () => <span>Info</span>,
  PanelLeft: () => <span>PanelLeft</span>,
  Layout: () => <span>Layout</span>,
  ToggleLeft: () => <span>ToggleLeft</span>,
  Menu: () => <span>Menu</span>,
  GitBranch: () => <span>GitBranch</span>,
  MessageSquare: () => <span>MessageSquare</span>,
  ChevronRight: () => <span>ChevronRight</span>,
  MoreHorizontal: () => <span>MoreHorizontal</span>,
  AlignLeft: () => <span>AlignLeft</span>,
  AlignCenter: () => <span>AlignCenter</span>,
  AlignRight: () => <span>AlignRight</span>,
  Bold: () => <span>Bold</span>,
  Italic: () => <span>Italic</span>,
  Underline: () => <span>Underline</span>,
  ArrowUp: () => <span>ArrowUp</span>,
  ArrowDown: () => <span>ArrowDown</span>,
  Maximize2: () => <span>Maximize2</span>,
  Save: () => <span>Save</span>,
  Folder: () => <span>Folder</span>,
  FilePlus: () => <span>FilePlus</span>,
  Move: () => <span>Move</span>,
  RotateCw: () => <span>RotateCw</span>,
  Trash: () => <span>Trash</span>,
  ImageIcon: () => <span>ImageIcon</span>,
  TypeIcon: () => <span>TypeIcon</span>,
  SquareIcon: () => <span>SquareIcon</span>,
  CircleIcon: () => <span>CircleIcon</span>,
  Diamond: () => <span>Diamond</span>,
  Hexagon: () => <span>Hexagon</span>,
  Star: () => <span>Star</span>,
  Triangle: () => <span>Triangle</span>,
  Pentagon: () => <span>Pentagon</span>,
  Octagon: () => <span>Octagon</span>,
  Cross: () => <span>Cross</span>,
  Cloud: () => <span>Cloud</span>,
  Heart: () => <span>Heart</span>,
  Bookmark: () => <span>Bookmark</span>,
  Flag: () => <span>Flag</span>,
  MapPin: () => <span>MapPin</span>,
  StickyNote: () => <span>StickyNote</span>,
  CreditCard: () => <span>CreditCard</span>,
  Monitor: () => <span>Monitor</span>,
  Smartphone: () => <span>Smartphone</span>,
  Tablet: () => <span>Tablet</span>,
  Laptop: () => <span>Laptop</span>,
  Tv: () => <span>Tv</span>,
  Camera: () => <span>Camera</span>,
  Video: () => <span>Video</span>,
  Mic: () => <span>Mic</span>,
  Volume2: () => <span>Volume2</span>,
  Play: () => <span>Play</span>,
  Pause: () => <span>Pause</span>,
  Stop: () => <span>Stop</span>,
  SkipBack: () => <span>SkipBack</span>,
  SkipForward: () => <span>SkipForward</span>,
  Radio: () => <span>Radio</span>,
  Cast: () => <span>Cast</span>,
  Airplay: () => <span>Airplay</span>,
  Bluetooth: () => <span>Bluetooth</span>,
  Wifi: () => <span>Wifi</span>,
  Battery: () => <span>Battery</span>,
  Power: () => <span>Power</span>,
  Sun: () => <span>Sun</span>,
  Moon: () => <span>Moon</span>,
  CloudRain: () => <span>CloudRain</span>,
  CloudSnow: () => <span>CloudSnow</span>,
  Wind: () => <span>Wind</span>,
  Thermometer: () => <span>Thermometer</span>,
  Droplet: () => <span>Droplet</span>,
  Flame: () => <span>Flame</span>,
  Snowflake: () => <span>Snowflake</span>,
  Zap: () => <span>Zap</span>,
  Fan: () => <span>Fan</span>,
  Home: () => <span>Home</span>,
  Building: () => <span>Building</span>,
  Building2: () => <span>Building2</span>,
  Factory: () => <span>Factory</span>,
  Warehouse: () => <span>Warehouse</span>,
  Store: () => <span>Store</span>,
  ShoppingCart: () => <span>ShoppingCart</span>,
  ShoppingBag: () => <span>ShoppingBag</span>,
  Gift: () => <span>Gift</span>,
  Package: () => <span>Package</span>,
  Truck: () => <span>Truck</span>,
  Ship: () => <span>Ship</span>,
  Plane: () => <span>Plane</span>,
  Car: () => <span>Car</span>,
  Bus: () => <span>Bus</span>,
  Train: () => <span>Train</span>,
  Bike: () => <span>Bike</span>,
  Navigation: () => <span>Navigation</span>,
  Compass: () => <span>Compass</span>,
  Globe: () => <span>Globe</span>,
  Map: () => <span>Map</span>,
  MapPinOff: () => <span>MapPinOff</span>,
  Hash: () => <span>Hash</span>,
  AtSign: () => <span>AtSign</span>,
  Mail: () => <span>Mail</span>,
  Phone: () => <span>Phone</span>,
  SmartphoneIcon: () => <span>SmartphoneIcon</span>,
  TabletIcon: () => <span>TabletIcon</span>,
  MonitorIcon: () => <span>MonitorIcon</span>,
  Keyboard: () => <span>Keyboard</span>,
  MousePointer: () => <span>MousePointer</span>,
  Printer: () => <span>Printer</span>,
  ScanLine: () => <span>ScanLine</span>,
  QrCode: () => <span>QrCode</span>,
  Barcode: () => <span>Barcode</span>,
  Rss: () => <span>Rss</span>,
  Share: () => <span>Share</span>,
  Share2: () => <span>Share2</span>,
  Link: () => <span>Link</span>,
  Paperclip: () => <span>Paperclip</span>,
  Unlink: () => <span>Unlink</span>,
  ExternalLink: () => <span>ExternalLink</span>,
  Search: () => <span>Search</span>,
  ZoomInIcon: () => <span>ZoomInIcon</span>,
  ZoomOutIcon: () => <span>ZoomOutIcon</span>,
  Filter: () => <span>Filter</span>,
  SlidersHorizontal: () => <span>SlidersHorizontal</span>,
  SlidersVertical: () => <span>SlidersVertical</span>,
  List: () => <span>List</span>,
  ListOrdered: () => <span>ListOrdered</span>,
  ListTodo: () => <span>ListTodo</span>,
  LayoutGrid: () => <span>LayoutGrid</span>,
  LayoutList: () => <span>LayoutList</span>,
  LayoutTemplateIcon: () => <span>LayoutTemplateIcon</span>,
  Columns: () => <span>Columns</span>,
  Rows: () => <span>Rows</span>,
  Grid: () => <span>Grid</span>,
  Grid2X2: () => <span>Grid2X2</span>,
  Grid3X3Icon: () => <span>Grid3X3Icon</span>,
  Divide: () => <span>Divide</span>,
  Percent: () => <span>Percent</span>,
  Calculator: () => <span>Calculator</span>,
  Receipt: () => <span>Receipt</span>,
  Wallet: () => <span>Wallet</span>,
  Banknote: () => <span>Banknote</span>,
  Coins: () => <span>Coins</span>,
  BadgeDollarSign: () => <span>BadgeDollarSign</span>,
  BadgeCent: () => <span>BadgeCent</span>,
  BadgeEuro: () => <span>BadgeEuro</span>,
  BadgePoundSterling: () => <span>BadgePoundSterling</span>,
  BadgeYen: () => <span>BadgeYen</span>,
  BadgeRupee: () => <span>BadgeRupee</span>,
  BadgeSwissFranc: () => <span>BadgeSwissFranc</span>,
  BadgeIndianRupee: () => <span>BadgeIndianRupee</span>,
  BadgeRussianRuble: () => <span>BadgeRussianRuble</span>,
  BadgeJapaneseYen: () => <span>BadgeJapaneseYen</span>,
  DollarSign: () => <span>DollarSign</span>,
  Cent: () => <span>Cent</span>,
  Euro: () => <span>Euro</span>,
  PoundSterling: () => <span>PoundSterling</span>,
  JapaneseYen: () => <span>JapaneseYen</span>,
  Ruble: () => <span>Ruble</span>,
  IndianRupee: () => <span>IndianRupee</span>,
  Bitcoin: () => <span>Bitcoin</span>,
  CreditCardIcon: () => <span>CreditCardIcon</span>,
  BadgeCheck: () => <span>BadgeCheck</span>,
  BadgeX: () => <span>BadgeX</span>,
  BadgeAlert: () => <span>BadgeAlert</span>,
  BadgeInfo: () => <span>BadgeInfo</span>,
  BadgeQuestion: () => <span>BadgeQuestion</span>,
  BadgePlus: () => <span>BadgePlus</span>,
  BadgeMinus: () => <span>BadgeMinus</span>,
  Clock: () => <span>Clock</span>,
  Timer: () => <span>Timer</span>,
  Hourglass: () => <span>Hourglass</span>,
  History: () => <span>History</span>,
  RotateCcw: () => <span>RotateCcw</span>,
  RotateCcwIcon: () => <span>RotateCcwIcon</span>,
  Undo: () => <span>Undo</span>,
  Redo: () => <span>Redo</span>,
  RefreshCw: () => <span>RefreshCw</span>,
  RefreshCcw: () => <span>RefreshCcw</span>,
  Repeat: () => <span>Repeat</span>,
  Repeat1: () => <span>Repeat1</span>,
  Shuffle: () => <span>Shuffle</span>,
  Activity: () => <span>Activity</span>,
  Pulse: () => <span>Pulse</span>,
  HeartPulse: () => <span>HeartPulse</span>,
  Stethoscope: () => <span>Stethoscope</span>,
  Syringe: () => <span>Syringe</span>,
  Pill: () => <span>Pill</span>,
  Capsule: () => <span>Capsule</span>,
  TabletSmartphone: () => <span>TabletSmartphone</span>,
  SmartphoneCharging: () => <span>SmartphoneCharging</span>,
  BatteryCharging: () => <span>BatteryCharging</span>,
  BatteryFull: () => <span>BatteryFull</span>,
  BatteryMedium: () => <span>BatteryMedium</span>,
  BatteryLow: () => <span>BatteryLow</span>,
  BatteryWarning: () => <span>BatteryWarning</span>,
  Plug: () => <span>Plug</span>,
  PlugZap: () => <span>PlugZap</span>,
  Cable: () => <span>Cable</span>,
  Usb: () => <span>Usb</span>,
  HardDrive: () => <span>HardDrive</span>,
  Database: () => <span>Database</span>,
  Server: () => <span>Server</span>,
  Network: () => <span>Network</span>,
  Shield: () => <span>Shield</span>,
  ShieldAlert: () => <span>ShieldAlert</span>,
  ShieldCheck: () => <span>ShieldCheck</span>,
  ShieldX: () => <span>ShieldX</span>,
  ShieldOff: () => <span>ShieldOff</span>,
  ShieldQuestion: () => <span>ShieldQuestion</span>,
  LockIcon: () => <span>LockIcon</span>,
  UnlockIcon: () => <span>UnlockIcon</span>,
  Key: () => <span>Key</span>,
  KeyRound: () => <span>KeyRound</span>,
  KeySquare: () => <span>KeySquare</span>,
  EyeIcon: () => <span>EyeIcon</span>,
  EyeOffIcon: () => <span>EyeOffIcon</span>,
  Fingerprint: () => <span>Fingerprint</span>,
  ScanFace: () => <span>ScanFace</span>,
  ScanFingerprint: () => <span>ScanFingerprint</span>,
  CircleUser: () => <span>CircleUser</span>,
  User: () => <span>User</span>,
  Users: () => <span>Users</span>,
  UserPlus: () => <span>UserPlus</span>,
  UserMinus: () => <span>UserMinus</span>,
  UserX: () => <span>UserX</span>,
  UserCheck: () => <span>UserCheck</span>,
  UserCog: () => <span>UserCog</span>,
  Smile: () => <span>Smile</span>,
  Frown: () => <span>Frown</span>,
  Meh: () => <span>Meh</span>,
  Laugh: () => <span>Laugh</span>,
  Annoyed: () => <span>Annoyed</span>,
  Dices: () => <span>Dices</span>,
  Dice1: () => <span>Dice1</span>,
  Dice2: () => <span>Dice2</span>,
  Dice3: () => <span>Dice3</span>,
  Dice4: () => <span>Dice4</span>,
  Dice5: () => <span>Dice5</span>,
  Dice6: () => <span>Dice6</span>,
  Gamepad: () => <span>Gamepad</span>,
  Gamepad2: () => <span>Gamepad2</span>,
  Trophy: () => <span>Trophy</span>,
  Medal: () => <span>Medal</span>,
  Award: () => <span>Award</span>,
  Crown: () => <span>Crown</span>,
  Gem: () => <span>Gem</span>,
  Lightbulb: () => <span>Lightbulb</span>,
  LightbulbOff: () => <span>LightbulbOff</span>,
  Flashlight: () => <span>Flashlight</span>,
  Lamp: () => <span>Lamp</span>,
  LampCeiling: () => <span>LampCeiling</span>,
  LampDesk: () => <span>LampDesk</span>,
  LampFloor: () => <span>LampFloor</span>,
  LampWallDown: () => <span>LampWallDown</span>,
  LampWallUp: () => <span>LampWallUp</span>,
  SunDim: () => <span>SunDim</span>,
  SunMedium: () => <span>SunMedium</span>,
  Sunrise: () => <span>Sunrise</span>,
  Sunset: () => <span>Sunset</span>,
  MoonStar: () => <span>MoonStar</span>,
  Sparkles: () => <span>Sparkles</span>,
  Bell: () => <span>Bell</span>,
  BellDot: () => <span>BellDot</span>,
  BellOff: () => <span>BellOff</span>,
  BellRing: () => <span>BellRing</span>,
  ThumbsUp: () => <span>ThumbsUp</span>,
  ThumbsDown: () => <span>ThumbsDown</span>,
  HelpCircle: () => <span>HelpCircle</span>,
  AlertCircle: () => <span>AlertCircle</span>,
  AlertTriangle: () => <span>AlertTriangle</span>,
  AlertOctagon: () => <span>AlertOctagon</span>,
  InfoIcon: () => <span>InfoIcon</span>,
  XCircle: () => <span>XCircle</span>,
  XOctagon: () => <span>XOctagon</span>,
  XSquare: () => <span>XSquare</span>,
  CheckCircle: () => <span>CheckCircle</span>,
  CheckSquare: () => <span>CheckSquare</span>,
  CheckCircle2: () => <span>CheckCircle2</span>,
}));

describe('App Grouping Functionality', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should render the app without crashing', () => {
    render(<App />);
    expect(screen.getByText(/start drawing/i)).toBeInTheDocument();
  });

  it('should show group button disabled when no selection', () => {
    render(<App />);
    const groupButton = screen.getByTitle(/group selected/i);
    expect(groupButton).toBeDisabled();
  });

  it('should show ungroup button disabled when no selection', () => {
    render(<App />);
    const ungroupButton = screen.getByTitle(/ungroup/i);
    expect(ungroupButton).toBeDisabled();
  });
});

describe('Grouping Logic', () => {
  it('canGroup should be true when 2+ shapes selected', () => {
    // This would require more complex integration testing
    // For now, we verify the UI state
    render(<App />);
    
    // Initially cannot group
    const groupButton = screen.getByTitle(/group selected/i);
    expect(groupButton).toBeDisabled();
  });

  it('should have keyboard shortcuts defined', () => {
    render(<App />);
    
    // Check that the toolbar shows keyboard shortcut hints
    const groupButton = screen.getByTitle(/ctrl\+g/i);
    expect(groupButton).toBeInTheDocument();
    
    const ungroupButton = screen.getByTitle(/ctrl\+shift\+g/i);
    expect(ungroupButton).toBeInTheDocument();
  });
});

describe('Properties Panel Grouping UI', () => {
  it('should not show grouping controls when no selection', () => {
    render(<App />);
    
    // The grouping controls in the properties panel only show when selection exists
    // We verify the panel doesn't show certain elements initially
    const selectButton = screen.getByTitle(/select \(box\)/i);
    expect(selectButton).toBeInTheDocument();
  });
});
