import { ShapeObject } from './types';

export interface LibraryCategory {
  id: string;
  name: string;
  icon: string;
  items: LibraryItem[];
}

export interface LibraryItem {
  id: string;
  name: string;
  thumbnail?: string;
  createShape: () => ShapeObject | ShapeObject[];
}

// Helper to generate unique IDs
let idCounter = 0;
const generateId = () => `lib-${Date.now()}-${idCounter++}`;

export const SHAPE_LIBRARY: LibraryCategory[] = [
  {
    id: 'ui-basic',
    name: 'Basic UI',
    icon: 'Layout',
    items: [
      {
        id: 'button',
        name: 'Button',
        createShape: () => ({
          id: generateId(),
          tool: 'rect',
          x: 0,
          y: 0,
          width: 120,
          height: 40,
          rotation: 0,
          stroke: '#3b82f6',
          strokeWidth: 2,
          fill: '#3b82f6',
        }),
      },
      {
        id: 'input-field',
        name: 'Input Field',
        createShape: () => ({
          id: generateId(),
          tool: 'rect',
          x: 0,
          y: 0,
          width: 200,
          height: 36,
          rotation: 0,
          stroke: '#d1d5db',
          strokeWidth: 1,
          fill: '#ffffff',
        }),
      },
      {
        id: 'card',
        name: 'Card',
        createShape: () => ({
          id: generateId(),
          tool: 'rect',
          x: 0,
          y: 0,
          width: 280,
          height: 180,
          rotation: 0,
          stroke: '#e5e7eb',
          strokeWidth: 1,
          fill: '#ffffff',
        }),
      },
      {
        id: 'circle-button',
        name: 'Circle Button',
        createShape: () => ({
          id: generateId(),
          tool: 'circle',
          x: 0,
          y: 0,
          radius: 24,
          rotation: 0,
          stroke: '#3b82f6',
          strokeWidth: 2,
          fill: '#3b82f6',
        }),
      },
    ],
  },
  {
    id: 'ui-controls',
    name: 'Controls',
    icon: 'ToggleLeft',
    items: [
      {
        id: 'checkbox',
        name: 'Checkbox',
        createShape: () => ({
          id: generateId(),
          tool: 'rect',
          x: 0,
          y: 0,
          width: 20,
          height: 20,
          rotation: 0,
          stroke: '#6b7280',
          strokeWidth: 2,
          fill: 'transparent',
        }),
      },
      {
        id: 'radio',
        name: 'Radio Button',
        createShape: () => ({
          id: generateId(),
          tool: 'circle',
          x: 0,
          y: 0,
          radius: 10,
          rotation: 0,
          stroke: '#6b7280',
          strokeWidth: 2,
          fill: 'transparent',
        }),
      },
      {
        id: 'toggle',
        name: 'Toggle Switch',
        createShape: () => ({
          id: generateId(),
          tool: 'rect',
          x: 0,
          y: 0,
          width: 48,
          height: 24,
          rotation: 0,
          stroke: '#10b981',
          strokeWidth: 2,
          fill: '#10b981',
        }),
      },
      {
        id: 'slider',
        name: 'Slider',
        createShape: () => [
          {
            id: generateId(),
            tool: 'rect',
            x: 0,
            y: 6,
            width: 100,
            height: 4,
            rotation: 0,
            stroke: '#d1d5db',
            strokeWidth: 1,
            fill: '#d1d5db',
          },
          {
            id: generateId(),
            tool: 'circle',
            x: 50,
            y: 8,
            radius: 8,
            rotation: 0,
            stroke: '#3b82f6',
            strokeWidth: 2,
            fill: '#ffffff',
          },
        ] as ShapeObject[],
      },
    ],
  },
  {
    id: 'navigation',
    name: 'Navigation',
    icon: 'Menu',
    items: [
      {
        id: 'navbar',
        name: 'Navigation Bar',
        createShape: () => ({
          id: generateId(),
          tool: 'rect',
          x: 0,
          y: 0,
          width: 320,
          height: 56,
          rotation: 0,
          stroke: '#1f2937',
          strokeWidth: 1,
          fill: '#1f2937',
        }),
      },
      {
        id: 'tab',
        name: 'Tab',
        createShape: () => ({
          id: generateId(),
          tool: 'rect',
          x: 0,
          y: 0,
          width: 80,
          height: 40,
          rotation: 0,
          stroke: '#e5e7eb',
          strokeWidth: 1,
          fill: '#f9fafb',
        }),
      },
      {
        id: 'hamburger',
        name: 'Menu Icon',
        createShape: () => [
          {
            id: generateId(),
            tool: 'rect',
            x: 0,
            y: 0,
            width: 24,
            height: 2,
            rotation: 0,
            stroke: '#374151',
            strokeWidth: 2,
            fill: '#374151',
          },
          {
            id: generateId(),
            tool: 'rect',
            x: 0,
            y: 8,
            width: 24,
            height: 2,
            rotation: 0,
            stroke: '#374151',
            strokeWidth: 2,
            fill: '#374151',
          },
          {
            id: generateId(),
            tool: 'rect',
            x: 0,
            y: 16,
            width: 24,
            height: 2,
            rotation: 0,
            stroke: '#374151',
            strokeWidth: 2,
            fill: '#374151',
          },
        ] as ShapeObject[],
      },
      {
        id: 'search-bar',
        name: 'Search Bar',
        createShape: () => ({
          id: generateId(),
          tool: 'rect',
          x: 0,
          y: 0,
          width: 240,
          height: 40,
          rotation: 0,
          stroke: '#d1d5db',
          strokeWidth: 1,
          fill: '#f9fafb',
        }),
      },
    ],
  },
  {
    id: 'flowchart',
    name: 'Flowchart',
    icon: 'GitBranch',
    items: [
      {
        id: 'process',
        name: 'Process',
        createShape: () => ({
          id: generateId(),
          tool: 'rect',
          x: 0,
          y: 0,
          width: 120,
          height: 60,
          rotation: 0,
          stroke: '#6b7280',
          strokeWidth: 2,
          fill: 'transparent',
        }),
      },
      {
        id: 'decision',
        name: 'Decision',
        createShape: () => ({
          id: generateId(),
          tool: 'rect',
          x: 0,
          y: 0,
          width: 100,
          height: 100,
          rotation: 45,
          stroke: '#6b7280',
          strokeWidth: 2,
          fill: 'transparent',
        }),
      },
      {
        id: 'terminator',
        name: 'Start/End',
        createShape: () => ({
          id: generateId(),
          tool: 'rect',
          x: 0,
          y: 0,
          width: 120,
          height: 50,
          rotation: 0,
          stroke: '#6b7280',
          strokeWidth: 2,
          fill: 'transparent',
        }),
      },
      {
        id: 'document',
        name: 'Document',
        createShape: () => ({
          id: generateId(),
          tool: 'rect',
          x: 0,
          y: 0,
          width: 100,
          height: 80,
          rotation: 0,
          stroke: '#6b7280',
          strokeWidth: 2,
          fill: 'transparent',
        }),
      },
    ],
  },
  {
    id: 'annotations',
    name: 'Annotations',
    icon: 'MessageSquare',
    items: [
      {
        id: 'speech-bubble',
        name: 'Speech Bubble',
        createShape: () => ({
          id: generateId(),
          tool: 'rect',
          x: 0,
          y: 0,
          width: 140,
          height: 80,
          rotation: 0,
          stroke: '#f59e0b',
          strokeWidth: 2,
          fill: '#fef3c7',
        }),
      },
      {
        id: 'callout-1',
        name: 'Callout 1',
        createShape: () => ({
          id: generateId(),
          tool: 'circle',
          x: 0,
          y: 0,
          radius: 12,
          rotation: 0,
          stroke: '#ef4444',
          strokeWidth: 2,
          fill: '#fef2f2',
        }),
      },
      {
        id: 'callout-2',
        name: 'Callout 2',
        createShape: () => ({
          id: generateId(),
          tool: 'circle',
          x: 0,
          y: 0,
          radius: 12,
          rotation: 0,
          stroke: '#f59e0b',
          strokeWidth: 2,
          fill: '#fffbeb',
        }),
      },
      {
        id: 'callout-3',
        name: 'Callout 3',
        createShape: () => ({
          id: generateId(),
          tool: 'circle',
          x: 0,
          y: 0,
          radius: 12,
          rotation: 0,
          stroke: '#10b981',
          strokeWidth: 2,
          fill: '#ecfdf5',
        }),
      },
    ],
  },
];
